### ISSUE TITLE
"徐睿"被再次错误拆分、合并

### ISSUE THREAD

**Issue by arkerny** [OIerDb-ng/OIerDb-data-generator#122]
### 选手姓名

徐睿

### 错误类别

错误拆分

### 错误详情

在 #9 #70 中被错误拆分，合并的徐睿同学再次被错误拆分、合并。
[UID89312](https://oier.baoshuo.dev/oier/89312) 的 WC2023🥈银牌 成绩应为 [UID84087](https://oier.baoshuo.dev/oier/84087) 的成绩

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
由于「徐睿」先前进行过手动合并，因此由于技术限制，此后再出现新的获奖记录时仍然需要进行手动合并，对此造成的不便敬请谅解。
