### ISSUE TITLE
年级错误

### ISSUE THREAD

**Issue by githut-user** [OIerDb-ng/OIerDb-data-generator#124]
### 选手姓名

李滕

### 错误类别

年级、学校信息有误

### 错误详情

我们是五四制，小学五年，初中四年，所以2022年应该是初四，2021年应该是初三，可以参照noi官网

https://www.xn--vuqs4zq3d.com/oier/127631

### 承诺

- [x] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
五四制问题，合并至 OIerDb-ng/OIerDb#25.
