### ISSUE TITLE
申请合并同一选手的成绩

### ISSUE THREAD

**Issue by lunasphere** [OIerDb-ng/OIerDb-data-generator#127]
### 选手姓名

苏逸恒

### 错误类别

错误拆分

### 错误详情

https://oier.baoshuo.dev/oier/63561 
https://oier.baoshuo.dev/oier/74063

由于2021年上学期该选手的学籍从初二跳到初三，上面两个链接实际上是同一名选手

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
由于技术限制，在本次手动合并之后如果再有新的获奖记录产生将无法自动合并。因此如果再有新的获奖记录产生可以参照 https://github.com/OIerDb-ng/OIerDb-data-generator/commit/af0aaaf91826b72b9fcb61b6dfd03d7510f62fc2 修改并发送 Pull Request，或者再次发出 Issue，对此造成的不便敬请谅解。
