### ISSUE TITLE
信息重复

### ISSUE THREAD

**Issue by ZhongTianrui** [OIerDb-ng/OIerDb-data-generator#129]
### 选手姓名

李子晨

### 错误类别

错误拆分

### 错误详情

李子晨信息重复

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by Molmin** [comment]
说详细点

两个北京的就是两个人啊

**Comment by renbaoshuo** [comment]
因年代久远，现关闭此 issue。如仍有疑问，请点击 reopen issue 继续讨论。
