### ISSUE TITLE
福建何宇轩信息错误

### ISSUE THREAD

**Issue by 1419903188** [OIerDb-ng/OIerDb-data-generator#132]
### 选手姓名

何宇轩

### 错误类别

年级、学校信息有误

### 错误详情

福建省何宇轩的普及组获奖年级应该是初二，后面年级全部低一级是因为出国了一年多之后回国，相当于多读一年初中

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
As intended. (特殊年级已用粉色标注)
