### ISSUE TITLE
"徐睿"被再次错误拆分、合并

### ISSUE THREAD

**Issue by djwj233** [OIerDb-ng/OIerDb-data-generator#140]
### 选手姓名

徐睿

### 错误类别

错误合并

### 错误详情

[UID89312](https://oier.baoshuo.dev/oier/89312) 的 “APIO2023 铜牌” 和 “NOI2023 金牌” 的获奖记录应是 [UID84087](https://oier.baoshuo.dev/oier/84087) 的成绩。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by arkerny** [comment]
@djwj233 我都已经反映过好多次了 qaq
