### ISSUE TITLE
选手-内蒙古的那一页很多选手ccf评级是0

### ISSUE THREAD

**Issue by youkeliao** [OIerDb-ng/OIerDb-data-generator#148]
### 选手姓名

刘恒嘉 等人

### 错误类别

其他

### 错误详情

https://oier.baoshuo.dev/oiers?province=%E5%86%85%E8%92%99%E5%8F%A4&page=1 在这里能看到一堆 0级的选手。话说ccf的评级不是从1开始吗

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
根据《[CCF关于开展中学生计算机程序设计能力等级评价的通知](https://www.noi.cn/xw/2019-08-26/715369.shtml)》，NOI 春季测试的成绩不参与 CCF 评级的计算。
