### ISSUE TITLE
选手年级错误

### ISSUE THREAD

**Issue by DarnedBuzzard70** [OIerDb-ng/OIerDb-data-generator#149]
### 选手姓名

张语诚

### 错误类别

年级、学校信息有误

### 错误详情

<img width="889" alt="image" src="https://github.com/OIerDb-ng/OIerDb-data-generator/assets/76857649/2e09a1c5-65e7-4053-b105-2dfd4ae7fdca">

<img width="889" alt="image" src="https://github-production-user-asset-6210df.s3.amazonaws.com/76857649/260293361-731c8693-f8f1-442e-834d-c25cfbd6b8f1.png">

如上图，选手初中时期年级均错误。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
五四制问题，合并至 OIerDb-ng/OIerDb#25.
