### ISSUE TITLE
广东地区”华南师范大学中山附属中学“应修改为”中山市华辰实验中学“

### ISSUE THREAD

**Issue by Xiz233** [OIerDb-ng/OIerDb-data-generator#15]
### 学校名称

华南师范大学中山附属中学

### 错误类别

其他

### 错误详情

学校改名了（
请看官网
![image](https://user-images.githubusercontent.com/99239482/202710898-1e7a262d-4d25-4325-ae18-759d49305cc7.png)
~~（虽然名字改了但是下面依旧显示旧名字的学校是屑）~~
[学校OIerDb地址](https://oier.baoshuo.dev/school/721)

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
https://baike.baidu.com/item/%E5%8D%8E%E5%8D%97%E5%B8%88%E8%8C%83%E5%A4%A7%E5%AD%A6%E4%B8%AD%E5%B1%B1%E9%99%84%E5%B1%9E%E4%B8%AD%E5%AD%A6/8620220

百度百科上似乎并没有更新？

**Comment by Xiz233** [comment]
> https://baike.baidu.com/item/%E5%8D%8E%E5%8D%97%E5%B8%88%E8%8C%83%E5%A4%A7%E5%AD%A6%E4%B8%AD%E5%B1%B1%E9%99%84%E5%B1%9E%E4%B8%AD%E5%AD%A6/8620220
> 
> 百度百科上似乎并没有更新？

~~（学校领导太懒了）~~
![image](https://user-images.githubusercontent.com/99239482/202712647-fe15acf4-1894-4991-ab1b-d76e437cba14.png)
官网发过公告
这样可以了吗？
