### ISSUE TITLE
年级错误

### ISSUE THREAD

**Issue by H-J-Granger** [OIerDb-ng/OIerDb-data-generator#154]
### 选手姓名

廖思宇

### 错误类别

年级、学校信息有误

### 错误详情

我是一名中国科学技术大学少年班学院的同学，今年高中毕业 1 年，但 OIerDb 上显示为高三。

![](https://github.com/OIerDb-ng/OIerDb-data-generator/assets/51706146/d36cf1e9-ae6a-4337-8848-dd1b55dc50e0)

### 承诺

- [x] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by onelittlechildawa** [comment]
我个人觉得没有必要修正这样的错误，毕竟这个是按年级推断的，也有省份六年级是在初中上的呀。。

**Comment by renbaoshuo** [comment]
因年代久远，现关闭此 issue。如仍有疑问，请点击 reopen issue 继续讨论。
