### ISSUE TITLE
请求更改“郑州中原一中实验学校”至“郑州市桐柏一中”

### ISSUE THREAD

**Issue by hafterain** [OIerDb-ng/OIerDb-data-generator#155]
### 学校名称

郑州中原一中实验学校

### 错误类别

其他

### 错误详情

“郑州中原一中实验学校”已于2023年更名为“郑州市桐柏一中”。CCF的报名系统中也已改为“郑州市桐柏一中”。
![image](https://github.com/OIerDb-ng/OIerDb-data-generator/assets/145349654/8c7faf41-f2fb-43d5-b57d-10c5ea02bc30)

在此请求更改“郑州中原一中实验学校”至“郑州市桐柏一中”。

- OIerDB中的学校链接：[https://oier.baoshuo.dev/school/1686](https://oier.baoshuo.dev/school/1686)
- [关于学校更名的参考链接](https://mp.weixin.qq.com/s/FWpLS4GvQspZtO221DE5kg#:~:text=%E5%81%9C%E6%AD%A2%E6%8B%9B%E7%94%9F%E4%B8%94%E6%A0%A1%E5%9D%80%E7%94%A8%E4%BA%8E%E4%B8%BE%E5%8A%9E%E5%85%AC%E5%8A%9E%E6%99%AE%E9%80%9A%E5%88%9D%E4%B8%AD%E7%9A%84%E5%AD%A6%E6%A0%A1%E6%9C%894%E6%89%80%EF%BC%8C%E5%88%86%E5%88%AB%E4%B8%BA%EF%BC%9A%E9%83%91%E5%B7%9E%E4%B8%AD%E5%8E%9F%E4%B8%80%E4%B8%AD%E5%AE%9E%E9%AA%8C%E5%AD%A6%E6%A0%A1)

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
没找到相关参考资料，给的链接中未出现 “郑州市桐柏一中” 一词，请提供更多资料，谢谢。

**Comment by hafterain** [comment]
@yhx-12243 

我校是民办学校转公，以下为补充参考链接。

[https://learning.sohu.com/a/648557424_120653457?qq-pf-to=pcqq.group#:~:text=%E6%94%BE%E9%A3%9E%E6%A2%A6%E6%83%B3%EF%BC%81-,%E9%83%91%E5%B7%9E%E6%A1%90%E6%9F%8F%E4%B8%80%E4%B8%AD,-%E4%B8%AD%E5%8E%9F%E4%B8%80%E4%B8%AD](https://learning.sohu.com/a/648557424_120653457?qq-pf-to=pcqq.group#:~:text=%E6%94%BE%E9%A3%9E%E6%A2%A6%E6%83%B3%EF%BC%81-,%E9%83%91%E5%B7%9E%E6%A1%90%E6%9F%8F%E4%B8%80%E4%B8%AD,-%E4%B8%AD%E5%8E%9F%E4%B8%80%E4%B8%AD)
