### ISSUE TITLE
曲晨铭的年级错误

### ISSUE THREAD

**Issue by quchenming114** [OIerDb-ng/OIerDb-data-generator#156]
### 学校名称

山东省文登第一中学

### 错误类别

其他

### 错误详情

因为山东威海是五四制，所以我现在是高一

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
五四制问题，合并至 OIerDb-ng/OIerDb#25.
