### ISSUE TITLE
关于我信息的错误拆分

### ISSUE THREAD

**Issue by FLAMEs0818** [OIerDb-ng/OIerDb-data-generator#170]
### 选手姓名

高启航

### 错误类别

错误拆分

### 错误详情

维护者，您好！

我是JL现役OIer高启航，现我将对我的错误信息拆分做出合并申请。

https://www.xn--vuqs4zq3d.com/oier/89996 与 https://www.xn--vuqs4zq3d.com/oier/98352 ，二者均为我本人，但是网站对我的信息做出了错误拆分。请在看过该 issue 后帮我将这两份信息合并，非常感谢。

辛苦了！

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by FLAMEs0818** [comment]
请问网站上的数据什么时候可以同步更新？咕咕咕。

**Comment by yhx-12243** [comment]
你可以刷新一下缓存，我这边看已经更新。

> 请问网站上的数据什么时候可以同步更新？咕咕咕。

**Comment by FLAMEs0818** [comment]
好的！十分感谢/bx
