### ISSUE TITLE
年级错误，申请更改

### ISSUE THREAD

**Issue by cancan114514** [OIerDb-ng/OIerDb-data-generator#188]
### 选手姓名

刘洪鑫

### 错误类别

年级、学校信息有误

### 错误详情

烟台市为5-4学制，所以我的年级是初四，网站没有初四选项，所以我现在显示为高一。
因此申请现在更改我为初三年级，谢谢

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
五四制问题，合并至 https://github.com/OIerDb-ng/OIerDb/issues/25.
