### ISSUE TITLE
反馈信息

### ISSUE THREAD

**Issue by RoyWu1207** [OIerDb-ng/OIerDb-data-generator#19]
### 选手姓名

吴承锦

### 错误类别

年级、学校信息有误

### 错误详情

年级目前初一
[https://oier.baoshuo.dev/oier/108238](url)

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yusancky** [comment]
结合数据来看，这个选手在五年级时曾参赛，但因只有一条 `小学` 的记录被默认为六年级参赛了。

[![](https://user-images.githubusercontent.com/83524927/216525213-38e886f4-b56a-4bbb-97ba-3a4daeb14793.jpeg)](https://github.com/OIerDb-ng/OIerDb-data-generator/blob/50d102c299f1cc958d043a32839ace250c7690d2/data/raw.txt#L108248)

改成 `五年级` 就可以解决问题了。

**Comment by renbaoshuo** [comment]
因年代久远，现关闭此 issue。如仍有疑问，请点击 reopen issue 继续讨论。
