### ISSUE TITLE
选手信息错误

### ISSUE THREAD

**Issue by zhanghanwen1214** [OIerDb-ng/OIerDb-data-generator#191]
### 选手姓名

张瀚文

### 错误类别

错误合并

### 错误详情

[https://oier.baoshuo.dev/oier/9735](url)
CSP2023入门广西个人报名南宁考点小学五年级一等获奖选手张瀚文，错误与NOIP2013提高二等奖湖南师范大学附属中学高二的同名选手合并

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by zhanghanwen1214** [comment]
[https://oier.baoshuo.dev/oier/9735](url)

**Comment by yhx-12243** [comment]
Duplicate with #190.
