### ISSUE TITLE
本人更名，数据被错误合并

### ISSUE THREAD

**Issue by chalatea** [OIerDb-ng/OIerDb-data-generator#196]
### 选手姓名

王奕然

### 错误类别

错误合并

### 错误详情

本人姓名王奕然，原名王嘉熙，OIerDb上的uid（应）为124427。在2022-2023学年在浙江省杭州滨和中学就读，并在2023年7月毕业，现就读于杭州第四中学。
在2023年8月份，本人在浙江省杭州市滨江区长河街道派出所将本人的姓名（原名 王嘉熙   身份证号码 330108200711270218）更换为了“王奕然”。
而现在在OIerDb上，我在浙江省杭州滨和中学uid124427的个人成就并未转移，并且我今年获得的“CSP-S 2023 二等奖”的奖项被并入到了去年在江苏淮安外国语学校的另一名王奕然（uid：151884）的身上。
本人现请求：将本人的档案（uid：124427）中的姓名更改为“王奕然”，并将错误合并的奖项转到我的档案中。
如果需要我更名的详细信息可以联系我（邮箱 chaladum@qq.com），我会在周末回家后将更名证明文件拍照给您。
万分麻烦您，不胜感激！

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by chalatea** [comment]
省流：
将[王奕然](https://oier.baoshuo.dev/oier/151884)的获奖记录“CSP S-2023 二等奖”和对应学校信息转移至 [王嘉熙](https://oier.baoshuo.dev/oier/124427)

**Comment by renbaoshuo** [comment]
因年代久远，现关闭此 issue。如仍有疑问，请点击 reopen issue 继续讨论。
