### ISSUE TITLE
关于 oier 163424

### ISSUE THREAD

**Issue by zhlzt** [OIerDb-ng/OIerDb-data-generator#207]
### 选手姓名

林正涛

### 错误类别

年级、学校信息有误

### 错误详情

林正涛目前是五年级，不是六年级。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
由于 CCF 并未提供小学选手的年级信息，故无法进行修改。待初中参赛后会自动修正。
