### ISSUE TITLE
浙江华维外国语学校民办转公办后的更名应合并

### ISSUE THREAD

**Issue by arkerny** [OIerDb-ng/OIerDb-data-generator#23]
### 学校名称

浙江华维外国语学校 绍兴市上虞区华维文澜中学

### 错误类别

错误拆分

### 错误详情

浙江华维外国语学校 ID：656
绍兴市上虞区华维文澜中学 ID：6890
民办转公办后的更名

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
1. 请问更名后的正式名称是哪一个名称？
2. 如有，请提供学校的更名公告/批复。

**Comment by arkerny** [comment]
[招生文件](http://xxgk.shangyu.gov.cn/art/2022/10/9/art_1229328137_3959470.html)
华维外国语学校是暂名，注册地址是同一个
