### ISSUE TITLE
学校错误

### ISSUE THREAD

**Issue by yzrbz** [OIerDb-ng/OIerDb-data-generator#238]
### 选手姓名

包昀卓

### 错误类别

年级、学校信息有误

### 错误详情

就读于成都市七中育才学校东湖校区，而不是成都七中育才学校

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
官方信息中 包昀卓 所在学校就是 成都七中育才学校，且数据库中不存在 成都市七中育才学校东湖校区 这一学校。

**Comment by yzrbz** [comment]
Oierdb中“成都市七中育才学校东湖校区”的网址 [](https://oier.baoshuo.dev/school/7413)

**Comment by yzrbz** [comment]
https://oier.baoshuo.dev/school/7413

**Comment by yzrbz** [comment]
@yhx-12243 我实际上就读于“成都市七中育才学校东湖校区”，至于为什么报了“成都七中育才学校”，是因为东湖校区是新学校，当时noi官网没有这个学校，只能选了本部
