### ISSUE TITLE
黎又豪（错误拆分）

### ISSUE THREAD

**Issue by bigball12345** [OIerDb-ng/OIerDb-data-generator#249]
### 选手姓名

黎又豪

### 错误类别

错误拆分

### 错误详情

NOI官网上的信息如下：
CSP-J/S2023第二轮入门级 | CCF-CSP-JS2023-20159 | 黎又豪 | 男 | 湖南 | 岳阳市湘一南湖学校/湖南省岳阳市途灵职业技能培训学校 | 初一 | 105 | 二等
该生是在湘一就读，在途灵培训信息学。目前全部分数都计入了岳阳市湘一南湖学校。
希望能部分计入到湖南省岳阳市途灵职业技能培训学校，谢谢！

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by Molmin** [comment]
OIerDb 记录的学校名字应为其学籍学校或者报名所在单位
