### ISSUE TITLE
拆分错误

### ISSUE THREAD

**Issue by bigball12345** [OIerDb-ng/OIerDb-data-generator#250]
### 选手姓名

罗星杰

### 错误类别

错误合并

### 错误详情

NOI官方信息：
CSP-J/S2023第二轮提高级 | CCF-CSP-JS2023-05721 | 罗星杰 | 男 | 湖南 | 怀化市雅礼实验学校/湖南省岳阳市途灵职业技能培训学校 | 初三 | 60 | 三等
该生是在怀化市雅礼实验学校就读，在岳阳市途灵职业技能培训学校学习信息学。目前全部分数都计入了怀化市雅礼实验学校。
希望能部分计入到湖南省岳阳市途灵职业技能培训学校，谢谢！

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
您好，

OIerDb 记录的学校名字应为其学籍学校或者报名所在单位，且与 CCF 的公示信息保持一致。

故我们无法对该条记录做出修改。
