### ISSUE TITLE
选手许若辰被错误拆分

### ISSUE THREAD

**Issue by hnxuruochen** [OIerDb-ng/OIerDb-data-generator#26]
### 选手姓名

许若辰

### 错误类别

错误拆分

### 错误详情

许若辰
207
95430

1. 两个账号是同一个人。
2. 19年用"湖南逐月教育科技有限公司"社会报名，该公司目前已经被注销。"湖南启信逐月教育科技有限公司"是另一家公司。
3. 20年、21年通过“湖南师范大学附属中学”社会报名。
4. 社会报名均只能用“小学/无”的年级。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
请问 08、09 两年的记录也是同一个人吗？

**Comment by hnxuruochen** [comment]
是的，07年进的雅礼高中，08年高一升高二，09年高二升高三，10年毕业。
