### ISSUE TITLE
选手被错误合并，学校有w误

### ISSUE THREAD

**Issue by MoraxNB** [OIerDb-ng/OIerDb-data-generator#263]
### 选手姓名

马浩轩

### 错误类别

错误合并

### 错误详情

我只有在 **2023** 年参加了 **CSP-S** 并获得 **55** 分，且我从未前往过辽宁。
![image](https://github.com/user-attachments/assets/e356ef04-6b15-4c72-a13a-3a466050ac80)
只有第一条是我，而且我仅初一，学校为**郑州枫杨外国语**，而**不是新枫杨**，新枫杨是**高中**，望修改，感谢

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
Resolved by 05616bb.
