### ISSUE TITLE
选手信息错误

### ISSUE THREAD

**Issue by lzh531** [OIerDb-ng/OIerDb-data-generator#271]
### 选手姓名

李卓翰

### 错误类别

错误合并

### 错误详情

重庆选手李卓翰（学校人民（融侨）小学校，六年级）在参加CSP2023 入门比赛后，获奖信息误和一名浙江的选手合并在了一起。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by gi-b716** [comment]
LGTM


\





\
