### ISSUE TITLE
选手已获奖，但信息漏掉了

### ISSUE THREAD

**Issue by Bennyhxz** [OIerDb-ng/OIerDb-data-generator#272]
### 选手姓名

黄浩

### 错误类别

其他

### 错误详情

广东省中山市东区远洋学校小学六年给学生 黄浩在 2023年 CSP-S 提高组 第二轮比赛中得分 55 ，已获得 三等奖证书，但在这里的数据库中却查不到相应的信息。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
Duplicated #273.
