### ISSUE TITLE
选手已获奖，但这里查询不到

### ISSUE THREAD

**Issue by Bennyhxz** [OIerDb-ng/OIerDb-data-generator#273]
### 选手姓名

黄浩

### 错误类别

其他

### 错误详情

广东省中山市东区远洋学校小学六年级学生黄浩在 2023 CSP/S 第二轮比赛中 取得 55 成绩，已取得三等奖证书，但这里却查询不到。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by caijianhong** [comment]
是被合并到了一个湖南选手上去，分裂一下就行了

**Comment by Bennyhxz** [comment]
您好：
&nbsp; &nbsp;请问是你们帮忙直接分裂&nbsp;还是&nbsp;要我再提另外的申请邮件？


&nbsp; &nbsp;谢谢。




NanBai
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OIerDb-ng/OIerDb-data-generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月29日(星期一) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OIerDb-ng/OIerDb-data-generator] 选手已获奖，但这里查询不到 (Issue #273)





 
是被合并到了一个湖南选手上去，分裂一下就行了

**Comment by caijianhong** [comment]
您好：
‍‍我已经帮你提出 PR 申请了，您的问题将很快被解决。


谢谢。
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月29日 14:06 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [OIerDb-ng/OIerDb-data-generator] 选手已获奖，但这里查询不到 (Issue #273) |
您好：
&nbsp; &nbsp;请问是你们帮忙直接分裂&nbsp;还是&nbsp;要我再提另外的申请邮件？


&nbsp; &nbsp;谢谢。




NanBai
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "OIerDb-ng/OIerDb-data-generator" ***@***.***&gt;;
发送时间:&nbsp;2024年7月29日(星期一) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OIerDb-ng/OIerDb-data-generator] 选手已获奖，但这里查询不到 (Issue #273)






是被合并到了一个湖南选手上去，分裂一下就行了

**Comment by Bennyhxz** [comment]
非常感谢！




NanBai
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OIerDb-ng/OIerDb-data-generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月31日(星期三) 凌晨2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OIerDb-ng/OIerDb-data-generator] 选手已获奖，但这里查询不到 (Issue #273)





 
Closed #273 as completed via #274.
