### ISSUE TITLE
李南希 数据合并

### ISSUE THREAD

**Issue by andyjhj** [OIerDb-ng/OIerDb-data-generator#276]
### 选手姓名

李南希

### 错误类别

错误合并

### 错误详情

下面2条是同一位选手，需要数据合并。
#           姓名       省份        年级       评分         CCF评级
7612    李南希    上海        六年级   1245.14   6
20630  李南希   上海         初一       255.75     0

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
请问他的初中入学是 2023 年还是 2024 年

**Comment by andyjhj** [comment]
您好，李南希2024年9月入学是初一。
上海是54学制，2023年是华师大二附中六年级，2024年9月是华师大二附中初一。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yhx-12243 ***@***.***&gt;
发送时间: 2024年8月8日 07:54
收件人: OIerDb-ng/OIerDb-data-generator ***@***.***&gt;
抄送: andyjhj ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [OIerDb-ng/OIerDb-data-generator] 李南希 数据合并 (Issue #276)





 
请问他的初中入学是 2023 年还是 2024 年

**Comment by yhx-12243** [comment]
> 您好，李南希2024年9月入学是初一。 上海是54学制，2023年是华师大二附中六年级，2024年9月是华师大二附中初一。 

那么就是说她参加 NGOI 的时候应当是六年级对吧。

**Comment by andyjhj** [comment]
是的，她参加 NGOI 的时候应当是六年级。




蒋慧军
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OIerDb-ng/OIerDb-data-generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月9日(星期五) 中午12:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OIerDb-ng/OIerDb-data-generator] 李南希 数据合并 (Issue #276)





  
您好，李南希2024年9月入学是初一。 上海是54学制，2023年是华师大二附中六年级，2024年9月是华师大二附中初一。
  
那么就是说她参加 NGOI 的时候应当是六年级对吧。
