### ISSUE TITLE
澳门IOI选手成绩缺失

### ISSUE THREAD

**Issue by tony808github** [OIerDb-ng/OIerDb-data-generator#285]
### 选手姓名

葉俊濠 李耀輝

### 错误类别

年级、学校信息有误

### 错误详情

https://moi-stats.mcs.mo/contests/external/
澳选手IOI成绩缺失

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
Duplicate #284.
