### ISSUE TITLE
北京一名选手年龄错误

### ISSUE THREAD

**Issue by lkjlkjlkj2012** [OIerDb-ng/OIerDb-data-generator#286]
### 选手姓名

刘康杰

### 错误类别

年级、学校信息有误

### 错误详情

省份：北京
就读学校：北京石油学院附属实验小学
                   中国人民大学附属中学
年级：现6年级
奖项：CSP2023入门 一等奖 5年级 北京石油学院附属实验小学

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
信息不足，默认认定为 6 年级，今年有奖项后会自动修正。
