### ISSUE TITLE
选手信息有误

### ISSUE THREAD

**Issue by Herobrine6265** [OIerDb-ng/OIerDb-data-generator#298]
### 选手姓名

张卓霖

### 错误类别

错误拆分

### 错误详情

陕西省 西安铁一中滨河高级中学 高三
UID：146307 190101

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
应该是你在报名 NOIP2023 的时候年级信息填写出错了
