### ISSUE TITLE
年级不对

### ISSUE THREAD

**Issue by GccGdb781** [OIerDb-ng/OIerDb-data-generator#306]
### 选手姓名

文励达

### 错误类别

年级、学校信息有误

### 错误详情

 年级信息有误，现（2024）年 5 年级，不是 6 年级

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
五年级之类问题不予处理，CCF 官方数据中不包含年级，明年参加比赛后自动修复。
