### ISSUE TITLE
我的年级记录错误

### ISSUE THREAD

**Issue by vectorlmn** [OIerDb-ng/OIerDb-data-generator#309]
### 选手姓名

柳默浓

### 错误类别

年级、学校信息有误

### 错误详情

我是现在的初三选手，由于 2023 在五四制区域参赛，记录为初三，今年转学到了六三制，仍然是初三，但是错误记录为了高一。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
forward #OIerDb-ng/OIerDb#25.
