### ISSUE TITLE
广东中山市华辰实验中学 选手 黄浩 被错误合并到福建省去了

### ISSUE THREAD

**Issue by Bennyhxz** [OIerDb-ng/OIerDb-data-generator#310]
### 选手姓名

黄浩

### 错误类别

错误合并

### 错误详情

选手黄浩 2023 年 小学六年级，就读于广东 中山市东区远洋学校，获 CSP2023提高 三等奖（55分），信息正确；

该选手 2024年 初中一年级，就读于广东 中山市华辰实验中学，获 CSP2024提高 三等奖（75分），但2024年的获奖信息被合并到福建省去了，信息错误。

烦请修正，谢谢。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
待 #349 合并后会自动修复。
