### ISSUE TITLE
年级错误

### ISSUE THREAD

**Issue by Jovenye** [OIerDb-ng/OIerDb-data-generator#315]
### 学校名称

温州市城南小学

### 错误类别

其他

### 错误详情

叶梓骁 温州市城南小学，年级为小学5年级

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
由于 CCF 并未提供小学选手的年级信息，故无法进行修改。待初中参赛后会自动修正。
