### ISSUE TITLE
选手信息合并错误

### ISSUE THREAD

**Issue by bit3725** [OIerDb-ng/OIerDb-data-generator#318]
### 选手姓名

王子轩

### 错误类别

错误合并

### 错误详情

同名选手，信息合并错误，麻烦修正，谢谢🙏 https://oier.baoshuo.dev/oier/51227

> CSP2024 入门 一等奖 | 260 / 400 | 4483 / 27177 | 北京 | 北京交通大学附属小学

这个目前应该是小学五年级

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
1. 待 #348 合并后会自动修复。
1. 由于 CCF 并未提供小学选手的年级信息，故无法进行修改。待初中参赛后会自动修正。
