### ISSUE TITLE
选手被错误合并

### ISSUE THREAD

**Issue by IloveNailong** [OIerDb-ng/OIerDb-data-generator#319]
### 选手姓名

王子轩

### 错误类别

错误合并

### 错误详情

本人来自重庆，在 CSP-2024 中仅报名 -S，但今天（20241120）OIerDb 爬数据时错误地将一浙江同名同年级选手的 -J 的成绩一并爬取。故希望 OIerDb 更正。
![wzxx](https://github.com/user-attachments/assets/2aedf496-ff9d-4490-a7c8-3988621ea965)

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
待 #349 合并后会自动修复。
