### ISSUE TITLE
学校有误

### ISSUE THREAD

**Issue by HeavenOJ** [OIerDb-ng/OIerDb-data-generator#32]
### 选手姓名

于嘉俊

### 错误类别

年级、学校信息有误

### 错误详情

我的学校是：[北京市朝阳区人大附中朝阳分校](https://www.xn--vuqs4zq3d.com/school/2729)

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
请问您指的是不是：**学校被错误拆分**？

**Comment by HeavenOJ** [comment]
您好
我指的是我的学校被填错了
我是北京市朝阳区人大附中朝阳分校&nbsp; &nbsp;的学生

---原始邮件---
发件人: "Baoshuo ***@***.***&gt;
发送时间: 2022年11月21日(周一) 下午2:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OIerDb-ng/OIerDb-data-generator] 学校有误 (Issue #32)




 
请问您指的是不是：学校被错误拆分？

**Comment by HeavenOJ** [comment]
OK这边显示改过来了
非常感谢

---原始邮件---
发件人: "Baoshuo ***@***.***&gt;
发送时间: 2022年11月22日(周二) 下午5:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OIerDb-ng/OIerDb-data-generator] 学校有误 (Issue #32)




 
那就是学校被错误合并了。。。
 
似乎「中国人民大学附属中学朝阳分校」和「中国人民大学附属中学朝阳学校」并不是同一所学校。
