### ISSUE TITLE
选手错误合并

### ISSUE THREAD

**Issue by woruo27** [OIerDb-ng/OIerDb-data-generator#320]
### 选手姓名

张润泽

### 错误类别

错误合并

### 错误详情

选手38369（江苏，无锡市教育科学研究院）的CSP-J&S 2024奖项（不包括NOIP 2013 提高）为选手43148（张润泽，咸阳彩虹学校、个人报名（西安））所有。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
Already fixed by 59e8c9f...beaa620.

**Comment by woruo27** [comment]
问题仍然存在。 @yhx-12243
