### ISSUE TITLE
18637 林泽宇选手被错误合并

### ISSUE THREAD

**Issue by flhsll** [OIerDb-ng/OIerDb-data-generator#332]
### 选手姓名

林泽宇

### 错误类别

错误合并

### 错误详情

林泽宇选手 是目前6年级的北京小学生，丰台第五小学。 18637 林泽宇选手 可能是之前的高中生。错误合并

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
Already fixed by 59e8c9f...beaa620.
