### ISSUE TITLE
年级错误

### ISSUE THREAD

**Issue by sunsichen** [OIerDb-ng/OIerDb-data-generator#338]
### 选手姓名

孙思辰

### 错误类别

年级、学校信息有误

### 错误详情

孙思辰目前读五年级上册，网站上登记信息显示六年级

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
五年级之类问题不予处理，CCF 官方数据中不包含年级，明年参加比赛后自动修复，同 #306。
