### ISSUE TITLE
CSP-J成绩失踪

### ISSUE THREAD

**Issue by jianghao0629** [OIerDb-ng/OIerDb-data-generator#356]
### 选手姓名

江昊

### 错误类别

其他

### 错误详情

CSP-J成绩失踪 原本的一等奖没了
![成绩](https://github.com/user-attachments/assets/d7a5bf5d-7d2b-4cab-8d97-dd0f916d5936)
![成绩2](https://github.com/user-attachments/assets/d3e788cc-20bb-4f4e-9c8c-e3006ae3e0a5)

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
Fixed in https://github.com/OIerDb-ng/OIerDb-data-generator/commit/6773f1111824e6d0f6b2cc8b71e751bda93baebc
