### ISSUE TITLE
年级，学校有误

### ISSUE THREAD

**Issue by zhangzirui66** [OIerDb-ng/OIerDb-data-generator#358]
### 选手姓名

张子睿

### 错误类别

年级、学校信息有误

### 错误详情

<https://oier.baoshuo.dev/oier/199378> 应为成都市石笋街小学校（一品天下分校）五年级学生。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
由于 CCF 并未提供小学选手的年级信息，故无法进行修改。待初中参赛后会自动修正。
