### ISSUE TITLE
年级有误

### ISSUE THREAD

**Issue by ReJustin** [OIerDb-ng/OIerDb-data-generator#359]
### 选手姓名

王祎嘉

### 错误类别

年级、学校信息有误

### 错误详情

年级应为五年级，而非六年级

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
由于 CCF 并未提供小学选手的年级信息，故无法进行修改。待初中参赛后会自动修正。
