### ISSUE TITLE
郑州外国语中学郭子祺信息异常合并

### ISSUE THREAD

**Issue by Qqi1007** [OIerDb-ng/OIerDb-data-generator#369]
### 选手姓名

郭子祺

### 错误类别

错误合并

### 错误详情

河南省郑州外国语中学的初二选手郭子祺与常州市的“郭子祺”信息异常合并，申请改回。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
无此问题，请使用官方网站 https://oier.baoshuo.dev/?query=%E9%83%AD%E5%AD%90%E7%A5%BA .
