### ISSUE TITLE
2024J成绩没有同步到Older里面来

### ISSUE THREAD

**Issue by yanlilin0522** [OIerDb-ng/OIerDb-data-generator#375]
### 选手姓名

严子浩

### 错误类别

其他

### 错误详情

我们今年是第一次参加CSP的考试，去年十月份入坑现在初二，这次J 400，S 250，广东省东莞市大岭山新风中学。现在是只有S的成绩没有J的成绩。能不能帮忙重新同步一下noi官网的数据。谢谢。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
Fixed in https://github.com/OIerDb-ng/OIerDb-data-generator/commit/6773f1111824e6d0f6b2cc8b71e751bda93baebc
