### ISSUE TITLE
Bug: 部分远古 OIer 年级计算错误

### ISSUE THREAD

**Issue by Molmin** [OIerDb-ng/OIerDb-data-generator#391]
例如 https://oier.baoshuo.dev/oier/140821 ，2004年NOI银牌不应该为高中毕业31年，而且奖项记录中显示年级为高中毕业10年。

不知道是不是近期一些改动产生的bug还是很早就有的，不过之前好像没见到？

**Comment by renbaoshuo** [comment]
与 https://github.com/OIerDb-ng/OIerDb-data-generator/issues/142 重复。
