### ISSUE TITLE
选手被错误合并

### ISSUE THREAD

**Issue by Xiao-zhiwen** [OIerDb-ng/OIerDb-data-generator#392]
### 选手姓名

肖智文

### 错误类别

错误合并

### 错误详情

赣州市第三中学 的 肖智文 和 江西师范大学附属中学 的 肖智文 不是同一个人。
江西师范大学附属中学 的 肖智文 和 南昌凤凰城上海外国语学校 的 肖智文 是同一个人。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
已修复.
