### ISSUE TITLE
请求合并"连云港市新海初级中学"和"新海初级中学"

### ISSUE THREAD

**Issue by EricWay1024** [OIerDb-ng/OIerDb-data-generator#406]
### 学校名称

连云港市新海初级中学

### 错误类别

其他

### 错误详情

目前, 连云港市新海初级中学有两个页面: 连云港新海初级中学 ( https://oier.baoshuo.dev/school/5878 ) 和新海初级中学( https://oier.baoshuo.dev/school/6706 ). 这是同一个学校, 请求将新海初级中学的数据并入连云港新海初级中学. 

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
fixed in bcf23b3a817f8301ba7ff720438065104d31beec
