### ISSUE TITLE
学校名称信息错误

### ISSUE THREAD

**Issue by tianbiandeshenghuo** [OIerDb-ng/OIerDb-data-generator#418]
### 学校名称

长沙市雨花区长郡雨花外国语左家塘学校

### 错误类别

名称有误

### 错误详情

长沙市雨花区长郡雨花外国语左家塘学校（编号4351），经手动查找获奖数据，确认大部分选手实际报名学校为“长沙市雨花区长郡雨花外国语学校”，左家塘学校仅为分校区（百度百科：https://baike.baidu.com/item/%E9%95%BF%E9%83%A1%E9%9B%A8%E8%8A%B1%E5%A4%96%E5%9B%BD%E8%AF%AD%E5%AD%A6%E6%A0%A1/14587823）

现申请修改名称为“长郡雨花外国语学校”。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
本问题已在 #415 中修复，正在等待合并。
