### ISSUE TITLE
学校、年级需要更新

### ISSUE THREAD

**Issue by rainx3** [OIerDb-ng/OIerDb-data-generator#428]
### 选手姓名

武坤承

### 错误类别

年级、学校信息有误

### 错误详情

我是武坤承，今年转学到了潍坊市高新区实验学校，年级是5年级，麻烦给更新一下吧，谢谢，顺祝工作顺利！

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
1. 官方数据上没有你的转学信息，不予更新（之后参加比赛后会自动更新/合并）；
2. 五年级之类问题不予处理，CCF 官方数据中不包含年级，明年参加比赛后自动修复，同 #306。
