### ISSUE TITLE
学校信息与CCF公示信息不符

### ISSUE THREAD

**Issue by bigball12345** [OIerDb-ng/OIerDb-data-generator#429]
### 学校名称

湖南省岳阳市途灵职业技能培训学校

### 错误类别

名称有误

### 错误详情

错误学校信息是：怀化市雅礼实验学校/湖南省岳阳市途灵职业技能培训学校，该学校的链接是：https://oier.33dai.wiki/school/8638。这个学校信息只有CSP2023公示信息中罗星杰同学是符合的（https://oier.33dai.wiki/oier/171368）。与CSP2024公示的全部信息都不符。

正确的学校信息是（CSP2024的公示信息）：湖南省岳阳市途灵职业技能培训学校，即岳阳市途灵职业技能培训学校。该学校的链接是：https://oier.33dai.wiki/school/6950。天眼查页面：https://www.tianyancha.com/company/3418483613

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
您访问的是镜像站点，并非官方运营的 OIerDb。

https://oier.baoshuo.dev/school/8638

在 oier.baoshuo.dev 上显示正常。
