### ISSUE TITLE
合并：江门市第一中学

### ISSUE THREAD

**Issue by debugger-zhang** [OIerDb-ng/OIerDb-data-generator#44]
### 学校名称

江门市第一中学

### 错误类别

错误拆分

### 错误详情

https://oier.baoshuo.dev/school/1668
https://oier.baoshuo.dev/school/5347

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yusancky** [comment]
他（她）指出的似乎是这两条数据：

https://github.com/OIerDb-ng/OIerDb-data-generator/blob/3b68a51afad74b9e090437aa5fc94254c3a91c82/data/school.txt#L1675

https://github.com/OIerDb-ng/OIerDb-data-generator/blob/3b68a51afad74b9e090437aa5fc94254c3a91c82/data/school.txt#L4682

两条数据对应的学校确实有可能是同一学校，且后者和前者分别是初中部与高中部。[^1]

> **Note**
> 仅有一名学生的数据可以进行「跨民称」的有效推测，其他学生都只有在前者就读高中时参赛（或外加在其它学校就读初中时参赛）的记录。

[^1]: 这里的「同一学校」是狭义的概念，指一所学校（某一校区）的两个名称。对于一所学校的初中部和高中部对外正式名称不同是否算在内，请根据实情处理。

**Comment by debugger-zhang** [comment]
不是这两条，似乎我要求合并的数据已经没有了。
