### ISSUE TITLE
有关于高中毕业年数的勘误

### ISSUE THREAD

**Issue by RaidenShogun219** [OIerDb-ng/OIerDb-data-generator#461]
### 选手姓名

邵辰航

### 错误类别

年级、学校信息有误

### 错误详情

我是学生本人，我高中休学了一年，所以高中到现在应该是毕业三年

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yhx-12243** [comment]
在**参加最后一次比赛之后**的休学与 OI 数据无关，不予更新，谢谢。
