### ISSUE TITLE
选手”李响“的奖项错误地被合并

### ISSUE THREAD

**Issue by hellolllllin** [OIerDb-ng/OIerDb-data-generator#64]
### 选手姓名

李响

### 错误类别

错误合并

### 错误详情

[link](https://oier.baoshuo.dev/oier/87359)

![image](https://user-images.githubusercontent.com/119287439/207265325-687b3faa-4255-4d08-b008-1cb3dcd0310a.png)

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yusancky** [comment]
duplicated #63
