### ISSUE TITLE
华师一附中 学校错误拆分

### ISSUE THREAD

**Issue by Fy5-FyFive** [OIerDb-ng/OIerDb-data-generator#67]
### 学校名称

湖北省华中师范大学第一附属中学/华中师范大学第一附属中学

### 错误类别

错误拆分

### 错误详情

湖北省华中师范大学第一附属中学 和 华中师范大学第一附属中学 为无歧义的同一所高中，被错误地拆成了两个学校项
ID：
华中师范大学第一附属中学：1797
湖北省华中师范大学第一附属中学：7126

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
#68
