### ISSUE TITLE
选手信息错误

### ISSUE THREAD

**Issue by 11jiang08** [OIerDb-ng/OIerDb-data-generator#83]
### 选手姓名

蒋文博

### 错误类别

错误合并

### 错误详情

在OIerDb上，目前读初一的”蒋文博“的就读学校为”上海民办欣竹中学“（学校名称有更改），且获奖信息应该是”2021 CSP-J 350分 1等“ ，CCF评级应为5级。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
此处的获奖记录是从 CCF 官方公布的获奖名单导入的，不接受与竞赛成绩相关的修改。

**Comment by 11jiang08** [comment]
你们获奖信息导错了都不改的？就这种工作态度？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OIerDb-ng/OIerDb-data-generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月5日(星期四) 上午8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OIerDb-ng/OIerDb-data-generator] 选手信息错误 (Issue #83)





 
此处的获奖记录是从 CCF 官方公布的获奖名单导入的，不接受与竞赛成绩相关的修改。

**Comment by renbaoshuo** [comment]
您并没有提供任何与您在该次竞赛中获得成绩相关的证明材料，因此我们无法验证您的请求的真实性。

**Comment by 11jiang08** [comment]
这是从noi官网搜出来的名字叫“蒋文博”的人的获奖记录。麻烦你们仔细核对，5-11属于同一个人，1-2属于同一个人，3属于一个人，4属于一个人。你们数据库的获奖信息是错的。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OIerDb-ng/OIerDb-data-generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月5日(星期四) 上午8:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OIerDb-ng/OIerDb-data-generator] 选手信息错误 (Issue #83)





 
您并没有提供任何与您在该次竞赛中获得成绩相关的证明材料，因此我们无法验证您的请求的真实性。

**Comment by renbaoshuo** [comment]
经过核查，您在 issue 最开始的表述有误。

事实上，您的获奖信息被错误合并到了一位重名的湖南选手中，但恰巧上海有一位和您同年级的重名选手，这导致了双方的理解错误。因此，只需要将这条被错误合并的信息拆分即可。

![Snipaste_2023-01-05_08-36-04](https://user-images.githubusercontent.com/47095648/210675747-becc583e-16e6-408b-b457-dcbf6ccc58d2.png)

▲ 错误合并

![Snipaste_2023-01-05_08-36-14](https://user-images.githubusercontent.com/47095648/210675759-3ab65bc3-b3ea-4cdb-b9b0-d0a4abc547fb.png)

▲ 重名选手

**Comment by 11jiang08** [comment]
> 经过核查，您在 issue 最开始的表述有误。
> 
> 事实上，您的获奖信息被错误合并到了一位重名的湖南选手中，但恰巧上海有一位和您同年级的重名选手，这导致了双方的理解错误。因此，只需要将这条被错误合并的信息拆分即可。
> 
> ![Snipaste_2023-01-05_08-36-04](https://user-images.githubusercontent.com/47095648/210675747-becc583e-16e6-408b-b457-dcbf6ccc58d2.png)
> 
> ▲ 错误合并
> 
> ![Snipaste_2023-01-05_08-36-14](https://user-images.githubusercontent.com/47095648/210675759-3ab65bc3-b3ea-4cdb-b9b0-d0a4abc547fb.png)
> 
> ▲ 重名选手

是这样的，上海有一位目前就读于初三的重名选手，还有一位目前就读于小学的重名选手。而我是初一

**Comment by 11jiang08** [comment]
这两位重名选手我都认识，所以很清楚。
