### ISSUE TITLE
选手年级信息有误

### ISSUE THREAD

**Issue by 11jiang08** [OIerDb-ng/OIerDb-data-generator#85]
### 选手姓名

蒋文博

### 错误类别

年级、学校信息有误

### 错误详情

您好，很不好意思再次打扰。但我想指出的是，[该选手](https://www.xn--vuqs4zq3d.com/oier/133754)的年级信息有误。该选手2021年在CSP-J获奖时为四年级，目前是五年级。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
CCF 对于小学选手的年级记录为「小学/无」，因此无法准确地断定一名小学生的年级。在进入初中并获得奖项后，此信息会自动更正。
