### ISSUE TITLE
我的学校不对

### ISSUE THREAD

**Issue by JR-OIer** [OIerDb-ng/OIerDb-data-generator#86]
### 学校名称

实验小学

### 错误类别

错误合并

### 错误详情

错误的学校ID:3722
全国到处都有实验小学啊，我在的应该是**莱阳市实验小学**（上面没有），给我整到蚌埠的小学去了
附上我的ID:29334

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
因年代久远，现关闭此 issue。如仍有疑问，请点击 reopen issue 继续讨论。
