### ISSUE TITLE
"徐睿"被错误拆分、合并

### ISSUE THREAD

**Issue by djwj233** [OIerDb-ng/OIerDb-data-generator#9]
### 选手姓名

徐睿

### 错误类别

错误合并

### 错误详情

<https://oier.baoshuo.dev/oier/84087> 的 CSP2021 提高的获奖信息被错误合并到 <https://oier.baoshuo.dev/oier/117371> 中去了。

学籍的变化是转学引起的。

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by renbaoshuo** [comment]
稍微有点乱，方便详细列出哪几条获奖记录是同一个人的吗？

**Comment by arkerny** [comment]
本人系徐睿的同学 [杭州徐睿](https://oier.baoshuo.dev/oier/117371) 的 CSP2021 提高一等奖获奖记录是 [绍兴徐睿](https://oier.baoshuo.dev/oier/84087) 的，绍兴徐睿在初三曾前往杭州学军中学教育集团文渊中学借读
