### ISSUE TITLE
“陈弘毅”被错误拆分

### ISSUE THREAD

**Issue by linakrbcs** [OIerDb-ng/OIerDb-data-generator#91]
### 选手姓名

陈弘毅

### 错误类别

错误拆分

### 错误详情

#14677 #41318
初中升高中

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yusancky** [comment]
看起来是 469876c29b2867d6a1f6604f2fe2202b1457832a 编号时的问题，我来处理一下吧。
