### ISSUE TITLE
学校信息错误

### ISSUE THREAD

**Issue by wenqwer** [OIerDb-ng/OIerDb-data-generator#92]
### 学校名称

长春市实验中学

### 错误类别

其他

### 错误详情

长春市实验中学未被建立，在学校一栏中无法找到，但我们学校有三位选手在数据库中，因此申请建立学校（三名选手的学校均为长春市实验中学）

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yusancky** [comment]
## 数据问题

实际上，贵校在**数据库中与「长春市净月实验中学」进行了合并**。
https://github.com/OIerDb-ng/OIerDb-data-generator/blob/50d102c299f1cc958d043a32839ace250c7690d2/data/school.txt#L1065

_文件格式为 `<省级行政区>,<地级行政区>,<学校正式名称>,<...别名列表>`。_

----

## 学校信息

- 从百度百科的数据上看：长春市净月实验中学是贵校的**初中部**，但贵校**也有设初中部**，暂**不能较好确定**两者是否是同一主体。
- 从地图信息看：贵校与长春市净月实验中学**极近且大概率连通**。
    ![地图（探索）](https://i.postimg.cc/mkqZPS2z/430-D9840-9-CB6-43-E1-9-A61-A08083-FB9-F26.jpg)
    ![地图（卫星）](https://i.postimg.cc/3wpGYd1F/F34-CCEB5-5007-4-BD6-AF52-3-B9-E8-F7-B2-FAB.jpg)

从以上数据看，我猜测两校是同一主体。但对于这一问题，我**尚未找到官方审批等消息**，暂时选择中立。

**Comment by wenqwer** [comment]
长春市实验中学为公立学校，长春市净月实验中学为私立学校，二者并无实质性联系，仅是地理位置上相近，希望贵方能完成学校划分



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月3日(周五) 凌晨3:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OIerDb-ng/OIerDb-data-generator] 学校信息错误 (Issue #92)




 
数据问题
 
实际上，贵校在数据库中与「长春市净月实验中学」进行了合并。
 https://github.com/OIerDb-ng/OIerDb-data-generator/blob/50d102c299f1cc958d043a32839ace250c7690d2/data/school.txt#L1065
 
文件格式为 <省级行政区&gt;,<地级行政区&gt;,<学校正式名称&gt;,<...别名列表&gt;。
 
 
学校信息
  
从百度百科的数据上看：长春市净月实验中学是贵校的初中部，但贵校也有设初中部，暂不能较好确定两者是否是同一主体。
 
从地图信息看：贵校与长春市净月实验中学极近且大概率连通。
 
 
  
从以上数据看，我猜测两校是同一主体。但对于这一问题，我尚未找到官方审批等消息，暂时选择中立。

**Comment by yusancky** [comment]
> 长春市实验中学为公立学校，长春市净月实验中学为私立学校，二者并无实质性联系

原来如此

**Comment by wenqwer** [comment]
确实这个比较容易出现问题，像我们周边有的家长打电话都能打错，哈哈哈哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月3日(周五) 上午8:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OIerDb-ng/OIerDb-data-generator] 学校信息错误 (Issue #92)




  
长春市实验中学为公立学校，长春市净月实验中学为私立学校，二者并无实质性联系
  
原来如此
