### ISSUE TITLE
WC2021的成绩经申诉后有变动

### ISSUE THREAD

**Issue by siskinxu** [OIerDb-ng/OIerDb-data-generator#95]
### 选手姓名

徐陈皓

### 错误类别

其他

### 错误详情

选手UID35106目前在OIerDB上WC2021的分数为119
进入NOI官方名单 https://www.noi.cn/upload/resources/file/2021/03/30/151827.html
发现他的分数已变为144，请求修改

### 承诺

- [X] 在提交这个 issue 前，我已确认我提交的信息是真实有效的。

**Comment by yusancky** [comment]
resolved via 50d102c299f1cc958d043a32839ace250c7690d2 ([line](https://github.com/OIerDb-ng/OIerDb-data-generator/commit/50d102c299f1cc958d043a32839ace250c7690d2#diff-2b706f6edd7c8e273aa2f98921b7c861dbb74e0ec11bef9d14addff1885b2a7bR115292))
